theme: jekyll-theme-hacker
title: Shark Strike Networks Blog Page
description: Show-casing all I've learned from my studies
show_downloads: true
google_analytics: 
author: 
  name: duology
  email: duologic.org@gmail.com
  url: https://k-connolly.github.io/Shark-Strike-Networks/

baseurl: "/Shark-Strike-Networks"

owner: duology
year: 2026
